FROM node:20-alpine
WORKDIR /app

# Instalar dependencias primero para aprovechar la caché
COPY package.json package-lock.json* ./
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto
EXPOSE 3000

# Usar el comando de desarrollo
CMD ["npm", "run", "dev"]